<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- Elements -->
	<xs:element name="ConversionRecord" type="ConversionRecordOfPaperToElectronicDocumentCType">
		<xs:annotation>
			<xs:documentation xml:lang="sk">D.6.3 Zlozeny datovy prvok pre zaznam o zaručenej konverzii.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!-- Complex Types -->
	<xs:complexType name="ConversionRecordOfPaperToElectronicDocumentCType">
		<xs:sequence>
			<xs:element name="OriginalDocumentInfo" type="OriginalDocumentInfoCType" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            Zakladne udaje o povodnom dokumente v listinnej podobe, resp. o viacerych povodnych dokumentoch, ktorych konverzia sa vykonava. Pre kazdy povodny dokument predlozeny ku konverzii sa v predlozenom poradi vedu v popise poli sekcie nasledujuce informacie:
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NewDocumentInfo" type="NewDocumentInfoCType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Zakladne udaje o dokumente v elektronickej podobe, ktory vznikol zarucenou konverziou z povodneho dokumentu, resp. z viacerych povodnych dokumentoch v listinnej podobe.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ConversionRecordEvidenceNumber" type="StringMax90ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            D.6.3.6 Uvadza sa evidencne cislo daneho zaznamu o  konverzii.
            [Poznamky: Po zavedeni centralnej evidencie zaznamov o vykonanej konverzii bude hodnota uvedena v tvare https://data.gov.sk/id/egov/conversion-record/ID, kde sa ako ID uvedie jedinecne cislo, resp. identifikator zaznamu.]
            [Hodnoty: Ak neexistuje struktura predpisana centralnou evidenciou, evidencne cislo zaznamu sa vytvara podla pravidiel prislusnej evidencie, v ktorej je zaznam evidovany.]
            Evidencne cislo zaznamu o zarucenej konverzii. Udaj identicky ako v osvedcovacej dolozke.
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="UsedDevice" type="StringMax1023ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            Uvadza sa udaj o pouzitom technickom alebo programovom prostriedku, ktoreho pouzitim je zarucena konverzia vykonana.
            Udaj sa uvadza vo forme identifikacie pouziteho prostriedku a vecneho opisu jeho pouzitia. Pri pouziti viacerych prostriedkov sa uvadzaju v poradi, v akom su pri konverzii pouzite.
            Pouziva sa obchodny nazov prostriedku. Ak je pouzity manualny prepis, toto sa uvadza na prislusnom mieste namiesto identifikaie pouziteho softveru.
            Priklad: softver „nazov“ pre skenovanie, OCR softver „nazov“ pre rozoznanie znakov a ulozenie vo formate „nazov“
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ConversionExecutionDateTime" type="dateTimeCetOrCest" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Datum a cas vykonania zarucenej konverzie vo formate podla ISO8601 s casovou zonou UTC+01:00 a +02:00 pre CEST.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="PersonPerformingConversion" type="PersonPerformingConversionCType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Udaje o osobe, ktora zarucenu konverziu vykonala.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OriginalDocumentInfoCType">
		<xs:sequence>
			<xs:element name="OriginalDocumentName" type="StringMax255ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            D.6.3.1 Obsahuje strucny vecny nazov povodneho dokumentu, ktory bol predmetom konverzie.
            Nazov povodneho dokumentu. Udaj identicky ako v osvedcovacej dolozke.
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OriginalDocumentOrder" type="NaturalNumberType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Poradie povodneho dokumentu. Uvadza sa poradie listinneho dokumentu tak, ako su povodne dokumenty predlozene ku konverzii.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OriginalDocumentType" type="StringMax255ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            D.6.3.3 Obsahuje strucny vecny opis druhu povodneho dokumentu.
            [Hodnoty: Nema predpisany obsah.
            Priklady pouzitia: kupna zmluva, rozhodnutie, uznesenie vlady Slovenskej republiky, ziadost, ohlasenie.]
            [Poznamky: Pouziva sa opis, ktory najvystiznejsie popisuje prislusny druh povodneho dokumentu.]
            Uvadza sa strucny vecny opis druhu povodneho dokumentu (napr. kupna zmluva, rozhodnutie, uznesenie vlady Slovenskej republiky ,ziadost, ohlasenie)
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OriginalDocumentNumberOfSheets" type="IntMax5ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Pocet listov. Udaj identicky ako v osvedcovacej dolozke.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OriginalDocumentNonEmptyPageCount" type="IntMax5ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Pocet neprazdnych stran. Udaj identicky ako v osvedcovacej dolozke.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OriginalDocumentPaperSize" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="PaperSize" type="MandatoryStringType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Format papiera. Udaj identicky ako v osvedcovacej dolozke.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="PaperSizeNumberOfSheets" type="NaturalNumberType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Pocet listov. Udaj identicky ako v osvedcovacej dolozke.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="DocumentSecurityElementsDetails" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Informacie o vsetkych bezpecnostnych prvkoch, ktore su na povodnom listinnom dokumente, resp. na vsetkych listinnych dokumentoch, ktore su predmetom konverzie. Tato sekcia moze popisovat viacero bezpecnostnych prvkov, alebo nemusi obsahovat popis ziadneho bezpecnostneho prvku, ak povodny listinny dokument taky neobsahuje. Pre kazdy bezpecnostny prvok sa uvadzaju nasledovne udaje:</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="OriginalDocumentSecurityElementsDescription" type="MandatoryStringType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">
                  D.6.3.5 Obsahuje vecny opis vsetkych identifikovanych prvkov povodneho dokumentu v listinnej podobe.
                  [Hodnoty: Popis bezpecnostneho prvku, napr. vlastnorucny podpis osoby, uradne osvedceny podpis osoby, okruhla peciatka so statnym znakom, reliefna peciatka, vodotlac a pod.]
                </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="OriginalDocumentSecurityElementsPage" type="IntMax5ReqType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Cislo strany v povodnom dokumente, na ktorom sa nachadza popisovany bezpecnostny prvok. Pocitaju sa neprazdne strany. Oznacenie strany v povodnom dokumente ak sa odlisuje od realneho poradia strany, sa neberie do uvahy.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="OriginalDocumentSecurityElementsSheet" type="IntMax5ReqType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Cislo listu v povodnom dokumente, na ktorom sa nachadza popisovany bezpecnostny prvok.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="OriginalDocumentSecurityElementsLocation" type="MandatoryStringType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Popis miesta na strane, kde je bezpecnostny prvok umiestneny (napr. vpravo hore, nalavo v strede a pod.).</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="NewDocumentSecurityElementsPage" type="IntMax5ReqType" minOccurs="1" maxOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="sk">Cislo strany v konvertovanom (novom) dokumente, na ktorom sa nachadza popisovany bezpecnostny prvok. Novy dokument vznika ako postupnost stran obsahujuca konvertovany obraz vsetkych povodnych dokumentov v poradi, v akom boli ku konverzii predlozene.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NewDocumentInfoCType">
		<xs:sequence>
			<xs:element name="NewDocumentName" type="StringMax255ReqType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Nazov novovzniknuteho dokumentu v elektronickej podobe, pod akym je ulozeny v podpisovom kontajneri spolu s osvedcovacou dolozkou (vysledok zarucenej konverzie).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NewDocumentFormat" type="MandatoryStringType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">
            Do pola sa  udava format  novovzniknuteho elektronickeho dokumentu. Identifikacia formatu dokumentu sa vykona v sulade  s vynosom Ministerstva financii Slovenskej republiky c. 55/2014 o standardoch pre informacne systemy verejnej spravy §57d ods. 1.: 1.„PDF/A-1“ – elektronicky dokument vo formate Portable Document Format vo verzii A-1 (PDF/A-1),2.„PDF/A-2“ – elektronicky dokument vo formate Portable Document Format vo verzii A-2 (PDF/A-2),3.„PNG“ – elektronicky dokument vo formate Portable Network Grapgics (.png)
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ElectronicFingerprintValue" type="Base64BinaryRequired" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Hodnota elektronickeho odtlacku (hash) novovzniknuteho  elektronickeho dokumentu, ktora je zapisana v kodovani BASE64.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ElectronicFingerprintCalculationMethod" type="MandatoryStringType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="sk">Meno kryptografickej funkcie, ktorou bol odtlacok novovzniknuteho elektronickeho dokumentu vypocitany. Identifikacia pouzitej kryptografickej funkcie pre vypocet elektronickeho odtlacku sa vykona v sulade s  § 11 ods. 1 pism. m) zakona c. 272/2016 Z. z. o doveryhodnych sluzbach pre elektronicke transakcie na vnutornom trhu a o zmene a doplneni niektorych zakonov (zakon o doveryhodnych sluzbach) (napr. „sha-256“).</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
  <!-- Osoba vykonavajuca zarucenu konverziu -->
  <xs:complexType name="PersonPerformingConversionCType">
    <xs:sequence>
      <xs:element name="PersonData" type="PersonDataCType" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PersonDataCType">
    <xs:sequence>
      <xs:element name="PhysicalPerson" type="PhysicalPersonCType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Oznacenie fyzickej osoby ktora vykonala zarucenu konverziu.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/PhysicalPerson"
            "@type": "pper:PhysicalPerson",
            "dct:references": "pper:PhysicalPerson"
            }
          </xs:appinfo>          
        </xs:annotation>
      </xs:element>
      <xs:element name="LegalSubject" type="LegalSubjectCType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Oznacenie osoby vykonavajucej zarucenu konverziu.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/LegalSubject"
            "@type": "lsub:LegalSubject",
            "dct:references": "lsub:LegalSubject"
            }
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ID" type="IDCType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Oznacenie identifikatora osoby vykonavajucej zarucenu konverziu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PhysicalPersonCType">
    <xs:sequence>
      <xs:element name="PersonName" type="PersonNameCType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Meno a priezvisko osoby vykonavajucej zarucenu konverziu.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/PhysicalPerson/PersonName"
            "@type": "pper:PhysicalPerson",
            "dct:references": "pper:PersonName"
            }
          </xs:appinfo>          
        </xs:annotation>
      </xs:element>
      <xs:element name="Position" type="StringMax1023ReqType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Funkcia alebo pracovne zaradenie osoby vykonavajucej zarucenu konverziu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PersonNameCType">
    <xs:sequence>
      <xs:element name="GivenName" type="StringMax255ReqType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Meno osoby vykonavajucej zarucenu konverziu. Obsahuje rodne meno, ktorym je nededena cast mena osoby.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/PhysicalPerson/PersonName/GivenName"
            "@type": "pper:PersonName",
            "dct:references": "pper:givenName"
            }
          </xs:appinfo>

        </xs:annotation>
      </xs:element>
      <xs:element name="FamilyName" type="StringMax255ReqType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Priezvisko osoby vykonavajucej zarucenu konverziu.</xs:documentation>
					<xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/PhysicalPerson/PersonName/FamilyName"
            "@type": "pper:PersonName",
            "dct:references": "pper:familyName"
            }
          </xs:appinfo>          
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LegalSubjectCType">
    <xs:sequence>
      <xs:element name="Name" type="StringMax1023ReqType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Uplny nazov pravnickej osoby vykonavajucej zarucenu konverziu.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/LegalSubject/Name"
            "@type": "lsub:LegalSubject",
            "dct:references": "lsub:name"
            }
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- End of complex types -->

  <!--Begin of Codelist types-->
  <xs:complexType name="IDCType">
    <xs:sequence>
      <xs:element name="IdentifierType" type="CodelistDataElementCType">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Zlozeny datovy prvok pre udaje zo zakladneho ciselnika obsahujuceho udaje o type pouziteho identifikatora osoby (ICO) vykonavajucej zarucenu konverziu. Pouziva sa ciselnik CL004001</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IdentifierValue" type="IdentifierValueType">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Hodnota pouziteho identifikatora (ICO). Hodnota musi byt uvedena podla vzoru https://data.gov.sk/id/legal-subject/ICO, kde ako ICO sa uvedie hodnota pouziteho identifikatora ICO.</xs:documentation>
          <xs:appinfo>
            {
            "@context": {
            "dct": "http://purl.org/dc/terms/",
            "lsub": "https://data.gov.sk/def/ontology/legal-subject/",
            "pper": "https://data.gov.sk/def/ontology/physical-person/",
            "foaf": "http://xmlns.com/foaf/0.1/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "skos": "http://www.w3.org/2004/02/skos/core#"
            },
            "@id": "https://data.gov.sk/id/egov/eform/50349287.ConversionRecordOfPaperToElectronicDocument.sk/1.0/ConversionRecordOfPaperToElectronicDocument/PersonPerformingConversion/PersonData/ID/IdentifierValue"
            "@type": "lsub:LegalID",
            "dct:type": "https://data.gov.sk/def/identifier-type/7"
            "dct:references": "skos:notation"
            }
          </xs:appinfo>          
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CodelistDataElementCType">
    <xs:sequence>
      <xs:element name="Codelist" type="CodelistCType">
        <xs:annotation>
          <xs:documentation>D.5 Zlozeny datovy prvok, ktory obsahuje polozku zo zakladneho ciselnika. Pravidla pouzitia: Pri prenose  nepodpisanych udajov vychadzajucich z udajov zakladneho cislenika je pouzitie tohto datoveho prvku povinne.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CodelistCType">
    <xs:sequence>
      <xs:element name="CodelistCode" type="CodelistCodeType">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Jedinecny kod zakladneho ciselnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CodelistItem" type="CodelistItemCType">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Zlozeny datovy prvok na popis datovej struktury polozky ciselnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CodelistItemCType">
    <xs:sequence>
      <xs:element name="ItemCode" type="ItemCodeStringRequired">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Jedinecny kod polozky ciselnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ItemName" type="ItemNameSCType">
        <xs:annotation>
          <xs:documentation xml:lang="sk">Uplny nazov polozky ciselnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ItemNameSCType">
    <xs:simpleContent>
      <xs:extension base="ItemNameStringRequired">
        <xs:attribute name="Language"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="NonCodelistDataType">
    <xs:annotation>
      <xs:documentation>D.3.4.1 Obsahuje volnu neciselnikovu hodnotu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="2047"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CodelistCodeString">
    <xs:restriction base="xs:string">
      <xs:maxLength value="100"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CodelistCodeType">
    <xs:restriction base="CodelistCodeString">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ItemCodeStringRequired">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="255"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ItemNameStringRequired">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="2047"/>
    </xs:restriction>
  </xs:simpleType>
  <!--End of Codelist types-->
  
	<!-- Simple types -->
  <xs:simpleType name="MandatoryStringType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NaturalNumberType">
    <xs:restriction base="xs:positiveInteger"/>
  </xs:simpleType>
  <xs:simpleType name="StringMax10OptType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax20ReqType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax90ReqType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="90"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax30OptType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax130ReqType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="130"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax255ReqType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="255"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax255OptType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="255"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax1023ReqType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="1023"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMax1023OptType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="1023"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="IdentifierValueType">
    <xs:restriction base="xs:string">
      <xs:pattern value="https:\/\/data\.gov\.sk\/id\/legal-subject\/([0-9]{8}|[0-9]{12})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="IntMax5ReqType">
    <xs:restriction base="xs:int">
      <xs:pattern value="\d{1,5}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Base64BinaryRequired">
    <xs:restriction base="xs:base64Binary">
      <xs:minLength value="1"></xs:minLength>
      <xs:maxLength value="1023"></xs:maxLength>
    </xs:restriction>
  </xs:simpleType>  
  <xs:simpleType name="dateTimeCetOrCest">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+01:00|\+02:00)"/>
    </xs:restriction>
  </xs:simpleType>
	<!-- End of simple types -->
</xs:schema>
