#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Marián Čuprík
# SPDX-License-Identifier: EUPL-1.2
# Regenerates Sources/Chevron7Kit/Attestation/Forms/OfficialFormFiles.swift from
# docs/reference/forms. Digests: SHA-256 over Canonical XML 1.0 without comments.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python3 - "$root" <<'PY'
import base64, hashlib, pathlib, re, subprocess, sys, tempfile
root = pathlib.Path(sys.argv[1])
forms = root / "docs/reference/forms"
files = [
    ("recordSchema", forms / "record-1.0/schema.xsd"),
    ("recordPresentation", forms / "record-1.0/form103.sb.xslt"),
    ("clauseSchema", forms / "clause-1.3/schema.xsd"),
    ("clausePresentation", forms / "clause-1.3/form.2.html2.xslt"),
]
def digest(path):
    stripped = re.sub(rb"<!--.*?-->", b"", path.read_bytes(), flags=re.S)
    with tempfile.NamedTemporaryFile(suffix=".xml") as tmp:
        tmp.write(stripped)
        tmp.flush()
        canonical = subprocess.run(["xmllint", "--c14n", tmp.name], check=True, capture_output=True).stdout
    return base64.b64encode(hashlib.sha256(canonical).digest()).decode()
out = [
    "// SPDX-FileCopyrightText: 2026 Marián Čuprík",
    "// SPDX-License-Identifier: EUPL-1.2",
    "// Generated by scripts/embed-official-forms.sh from docs/reference/forms. Do not edit.",
    "",
    "import Foundation",
    "",
    "enum OfficialFormFiles {",
]
for name, path in files:
    out.append(f'    static let {name} = Data(base64Encoded: "{base64.b64encode(path.read_bytes()).decode()}")!')
    out.append(f'    static let {name}Digest = "{digest(path)}"')
out.append("}")
target = root / "Sources/Chevron7Kit/Attestation/Forms/OfficialFormFiles.swift"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text("\n".join(out) + "\n")
print(f"wrote {target}")
PY
