<?xml version="1.0" encoding="utf-8"?><xs:schema targetNamespace="http://schemas.datacontract.org/2004/07/Ditec.Iam.Dol.Enums" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/Ditec.Iam.Dol.Enums"><xs:complexType name="AuthenticationType"><xs:simpleContent><xs:extension base="xs:string"/></xs:simpleContent></xs:complexType><xs:element name="AuthenticationType" nillable="true" type="tns:AuthenticationType"/><xs:complexType name="ArrayOfAuthenticationType"><xs:sequence><xs:element minOccurs="0" maxOccurs="unbounded" form="qualified" name="AuthenticationType" nillable="true" type="tns:AuthenticationType"/></xs:sequence></xs:complexType><xs:element name="ArrayOfAuthenticationType" nillable="true" type="tns:ArrayOfAuthenticationType"/></xs:schema>