name: macOS Package on Main

on:
  push:
    branches: [main]

jobs:
  macos-package:
    environment: packaging
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "24.0.1+11"
          distribution: "liberica"
          java-package: "jdk+fx"

      - name: Cache local Maven repository and JDK cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/jdkCache
          key: macos-main-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            macos-main-maven-

      - name: Disable macOS signing
        shell: bash
        run: |
          sed -i.bak 's/^mac.sign=.*/mac.sign=0/' src/main/resources/digital/slovensko/autogram/build.properties

      - name: Package with Maven
        run: ./mvnw -B -C -V package -P system-jdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Autogram-macOS
          path: |
            target/*.pkg
            target/*.dmg

